### ISSUE TITLE
Get columns dinamically

### ISSUE THREAD

**Issue by joaoftrodrigues** [KnownUsername/Countries_CSV-to-HTML-and-LaTeX-formats#5]
Currently is being used static formula, which means, it's being used directly, the columns' names.
It's intended to get the columns dynamically - the program must identify them.

# Tasks
- [x] Change class Country (remove attributes)
- [x] Create method to obtain the columns' names
- [x] Test with both csv files

### Change class Country
All attributes must be removed, as the intention is to add new ones. The idea is to add those attributes from lexer file, by using _setattr_ method.

### Create method to obtain the columns' names
Decompose the file, collecting columns' names first, and then letting it process the rest of the file, being it, columns' values.

### Test with both csv files
With all implemented, test the results with both csv files. 
**Note:** Use first the smallest one - _small_text.csv_ , for easier comparison of results

**Comment by joaoftrodrigues** [comment]
### Changed way of implement. 

Insted of splitting the csv file in 2, it was created 2 states - **header** and **body**, where header retrieves columns' names, while body retrieves data.
